version: '3'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch 
    environment:
      - discovery.type=single-node    
      - cluster.name=docker-cluster   
      - bootstrap.memory_lock=true    
      - xpack.security.enabled=true  
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "TZ=Asia/Tokyo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "I18N_LOCALE=ja-JP"
volumes:
  elasticsearch:
    driver: 'local'